//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Retail Store
//  @ File Name : @CUSTOMER.java
//  @ Date : @14/09/2018
//  @ Author : @Vijayakumar
//
//




public class CUSTOMER
{
  public Object NAME;
  public Object ADDRESS;
  public Object EMAIL_ID;
  public Object TYPE;
  public void UpdateProfile()
  {
  
  }
}
