//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Retail Store
//  @ File Name : @SHOPPING CART.java
//  @ Date : @14/09/2018
//  @ Author : @Vijayakumar

public class SHOPPINGCART
{
  public Object PROD_ID;
  public Object Qty;
  public void additem()
  {
  
  }
  
  public void deleteItem()
  {
  
  }
  
  public void ChkOut()
  {
  
  }
}
