//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Retail Store
//  @ File Name : @USER.java
//  @ Date : @14/09/2018
//  @ Author : @Vijayakumar
//
//




public class USER
{
  public Object USER_ID;
  public Object PWD;
  public void Verify()
  {
  
  }
}
